# Домашнее задание 7

(прислать до 02:00 29.03.2020)

Домашнее задание выполняется в этом же Jupyter Notebook'e и присылается мне в Piazza через Private Post.
Файл с Вашим решением должен называться ```Surname_HW#```, где вместо ```Surname``` Вы пишите свою фамилию латиницей, а вместо ```#``` - номер домашнего задания. 
Решение каждой задачи необходимо поместить после её условия.

Пожалуйста, пишите свои решения чётко и понятно. 
При полном запуске Вашего решения (Kernel -> Restart & Run All) все ячейки должны выполняться без ошибок. 

## Задача 1 (5 pts)

Упражнение 2.1. из [книги лектора](https://arxiv.org/ftp/arxiv/papers/1711/1711.00394.pdf).  

### Решение

Мы рассматриваем выпуклые негладкие функции, для которых $\forall x, y \in Q\ \ \|\nabla f(y) - \nabla f(x) \|_2 \leq L_0 < \infty$. 

Имеем оценку $f(\overline x^N) - f(x^*) \leq \frac{LR^2}{2N}+\delta\ \ \ (2.22)$ для метода $x^{k+1} = \pi_Q(x^k - h \cdot \nabla f(x^k)\ \ \ (2.6)$ с длиной шага $h = \frac{1}{L}$ (здесь $\overline x^N = \frac{1}{N}\sum_{k=1}{N}x^k$).

Ранее в книге было показано, что если $\forall x, y\ \ \|\nabla f(y) - \nabla f(x) \|_2 \leq L_{\nu}\|x-y\|_2^{\nu}$. Подставим   $\nu=0$ и получим $L = \frac{L_0^2}{2\delta}$. Подставим выражение для $L$ в правую часть $(2.22)$ и получим $\frac{L_0^2R^2}{4N\delta} + \delta$, ($R = \|x^*-x^0\|_2$). Минимизируем полученное выражение пo $\delta$. Для этого продифференцируем это выражение пo $\delta$ и приравняем производную к нулю:

$$-\frac{L_0^2R^2}{4N\delta^2} + 1$

$$\delta^* = \sqrt{\frac{L_0^2R^2}{4N}} = \frac{L_0R}{2\sqrt{N}}$$

Теперь подставим $\delta = \delta^*$ в правую часть оценки $(2.22)$. Получим

$$f(\overline x^N) - f(x^*) \leq \frac{L_0R}{\sqrt{N}}$$

Теперь помучаемся с нижней оценкой.

По заданному $N \leq n-1$ определим 

$$f(x) = F_{N+1}(x) = L_0 \cdot \max_{1 \leq i \leq N+1} x_i + \frac{\mu}{2} \|x\|^2_2 = L_0 \cdot \max_{1 \leq i \leq N+1} x_i + \frac{\mu}{2} \sum_{i=1}^n x^2_i \ \ \ (1)$$

Здесь $\mu = \frac{L_0}{R\sqrt{N+1}}$.

Найдём $x^*$. Заметим, что в первом слагаемом целевой функции $\max$ берётся только по первым $N+1$ компонентам вектора $x$. Остальные не влияют на этот $\max$. То есть, компоненты $x_{N+2}, \dots, x_n$ влияют только на сумму  $\frac{\mu}{2} \sum_{i=1}^n x^2_i $. Видно, что минимум достигается при $x_{N+2} = \dots = x_n=0$. Теперь рассмотрим первые $N+1$ компонент. Очевидно, что минимум достигается когда они не больше нуля. Тогда если $x_i < x_j \leq 0$, то $x_i < x_j \leq \max\limits_{1 \leq k \leq N+1} x_k$, а также $|x_i| > |x_j|$. А теперь мы можем изменить значение $x_i$ и увеличить его до $x_i = x_j$. При этом $\max_{1 \leq i \leq N+1} x_i$ не изменится, а сумма квадратов уменьшится. Поэтому минимум достигается в точке, в которой $x_1 = \dots = x_{N+1} = \tau \leq 0$.

Итак, $x^*$ имеет вид $x^* = (\tau, \dots, \tau, 0, \dots, 0)$, где в начале $N+1$ буква $\tau$. Подставим это в выражение $(1)$ и минимизируем его по $\tau$. 

$$\min_{\tau}  L_0 \tau + \frac{\mu(N+1)}{2} \tau^2$$

$$ L_0  + \mu(N+1) \tau^* = 0$$

$$\tau^* = -\frac{L_0}{ \mu(N+1)} = -\frac{R}{\sqrt{N+1}}$$

$$f(x^*) = -\frac{L_0R}{2\sqrt{N+1}} < 0$$

Пусть $x^0 = 0$.

Докажем по индукции, что при $k \leq N$ при $i > k$ выполнено $x_i^k=0$ с точностью до перестановки индексов. База понятна.

Теперь предположим, что утверждение верно для шага $k-1$. 

Найдём решения уравнения $\partial f(x) = 0$.

$$ L_0 \partial \max_{1 \leq i \leq N+1} x_i + \mu x = 0$$

$$x = - \frac{L_0}{\mu} \partial \max_{1 \leq i \leq N+1}$$

Субдифференциал $\partial \max_{1 \leq i \leq N+1} x^{k-1}_i = Lin\{e_i | i \in I\}$, где $I$ -- множество индексов $i$, таких что $x^{k-1}_i = \max_{1 \leq i \leq N+1} x^{k-1}_i = 0$. То есть, $\partial \max_{1 \leq i \leq N+1} x^{k-1}_i = Lin\{e_k, \dots, e_{N+1}\}$. В худшем случае мы выберем из субифференциала какой-то орт $e_i$, так как нам надо оставить как можно больше нулевых компонент. Для порядка возьмём $e_k$. Тогда $x^k_{k+1} = \dots = x^k_{N+1} = 0$, и $ \max_{1 \leq i \leq N+1} x^k_i = 0$ в силу того что $k \leq n$. Переход доказан.

По доказанному выше $f(x^N) = L_0 \max_{1 \leq i \leq N+1} x^N_i + \frac{\mu}{2} \|x\|^2_2 = 0 + \frac{\mu}{2} \|x\|^2_2  \geq 0$. А значит, $f(x^N) - f(x^*) = F_{N+1}(x^N) - F_{N+1}(x^*) \geq - F_{N+1}(x^*) = \frac{L_0R}{2\sqrt{N+1}} = \frac{L_0^2}{2\mu(N+1)}$. Оценка доказана.

## Задача 2 (5 pts)

- (0.5 pts) Пусть Вам дано $m$ векторов из $\mathbb{R}^n$, про которых известно что они сгенерированы из некоторого нормального распределения с параметрами $(\mu, \Sigma)$. Более того, известно, что $\Sigma^{-1}$ разрежена, то есть много пар компонент векторов условно независимы. Сгенерируйте данные, которые удовлетворяют этим требованиям для $n = 100$ и $m = 500$. Если последующие пункты будут долго считаться, уменьшите эти параметры
- (1 pts) Теперь поставьте задачу поиска оценки матрицы $\Sigma^{-1}$ на основе оценки максимального правдоподобия
- Добавьте к Вашей постановке ограничение на то, что матрица $\Sigma^{-1}$ разрежена. Это делается добавлением к целевой функции слагаемого вида $\lambda \sum_{i < j} |(\Sigma^{-1})_{ij}|$, то есть аналог $\ell_1$ регуляризации для задачи наменьших квадратов, только теперь у нас разрежен не вектор, а матрица
- (1 pts) Получите выражение для проксимального оператора для функции $\lambda \sum_{i < j} |(\Sigma^{-1})_{ij}|$
- (1 pts) Сравните сходимость субградиентного метода и проксимального градиентного метода для этой задачи
- (1 pts) Проанализируйте как влияет значение параметра $\lambda$ на близость решения к точному значению матрицы, которое использовалось при генерации данных
- (0.5 pts) Сравните скорость решения рассмотренными методами со скоростью решения с помощью CVXPy

In [4]:
import numpy as np

n = 5
m = 10

mu = np.random.randn(n)
sig = np.random.randn(n)
sigma_inv05 = np.diag(sig) # Это матрица \Sigma^{-1/2}
print
for i in range(n):
    for j in range(i+1, n):
        sigma_inv05[i][j] += np.random.binomial(size=1, n=1, p = 0.1) * np.random.randn(1)
        sigma_inv05[j][i] = sigma_inv05[i][j]
sigma_inv05 = sigma_inv05.dot(sigma_inv05.T) # Это матрица \Sigma^{-1/2}
sigma_inv = sigma_inv05.dot(sigma_inv05) # \Sigma^{-1}
sigma = np.linalg.inv(sigma_inv) # \Sigma
print(sigma_inv)
print(sigma)

V = np.random.randn(m, n).dot(np.linalg.inv(sigma_inv05))
for i in range(m):
    V[i] += mu
print(len(V[0]))

[[0.20209937 0.         0.         0.         0.        ]
 [0.         0.32157598 0.         0.         0.        ]
 [0.         0.         0.00200372 0.         0.        ]
 [0.         0.         0.         0.4962514  0.        ]
 [0.         0.         0.         0.         0.00921904]]
[[  4.94806086   0.           0.           0.           0.        ]
 [  0.           3.10968499   0.           0.           0.        ]
 [  0.           0.         499.07238837   0.           0.        ]
 [  0.           0.           0.           2.01510766   0.        ]
 [  0.           0.           0.           0.         108.47113934]]
5


### Пункт 1

У нормальных случайных векторов есть своство: если $\xi \sim N(0, I)$, то $\Sigma^{1/2}\xi + \mu \sim N(\mu, \Sigma^{1/2}(\Sigma^{1/2})^{\top}) \sim N(\mu, \Sigma)$. Это мы использовали в том числе и для генерации 

### Пункт 3

Получим выражение для проксимального оператора функции $f(\Sigma^{-1}) = \lambda \sum_{i < j} |(\Sigma^{-1})_{ij}|$. Мы аппроксимируем искомую матрицу симметричной матрицей, поэтому можно считать, что проксимальный оператор определён только на симметричных матрицах.

$$prox_{\alpha f}(X) = \arg\min_U \left( f(U) + \frac{1}{2 \alpha} \|U-X\|^2_F \right) = \arg\min_U \left( \sum_{i < j}\left( \lambda |U_{ij}|+ \frac{1}{ \alpha} (U_{ij}-X_{ij})^2 \right) \right)$$

В последней сумме слагаемые не зависят друг от друга, поэтому можно минимизировать по отдельности каждое из них.

$$\min_{U_{ij}}\ \  \lambda |U_{ij}|+ \frac{1}{ \alpha} (U_{ij}-X_{ij})^2 $$

Эту задачу решаем аналогично пункту 1 из задачи 3. Получаем, что 

\begin{align}
(prox_{\alpha f}(X))_{ij} =
\begin{cases}
x_{ij} - \frac{\lambda\alpha}{2} & x_{ij} > \frac{\lambda\alpha}{2}  \\
0 &- \frac{\lambda\alpha}{2}  \leq x_{ij} \leq \frac{\lambda\alpha}{2} \\
x_{ij} + \frac{\lambda\alpha}{2}  & x_{ij} < -\frac{\lambda\alpha}{2} 
\end{cases}
\end{align}

## Задача 3 (6 pts)

- (2 pts) Выведите аналитический вид проксимального оператора для функции $|x|$

- (2 pts) Покажите, что точка минимума $x^*$ выпуклой функции $f(x)$ является неподвижной точкой проксимального оператора, то есть

$$
x^* = prox_f(x^*)
$$

- (2 pts) Сравните сходимость (по итерациям и по времени) проксимального метода и градиентного спуска для задачи

 $$
 \min \frac{1}{2}x^\top A x - b^{\top}x,
 $$
 
 где $A \in \mathbb{S}^N_+$, при увеличении размера шага. Убедитесь, что градиентный спуск начинает расходиться, а проксимальный метод – нет. Как увеличение шага влияет на сходимость проксимального метода?

### Пункт 1

$$f(x) = |x|$$

$$prox_{\alpha f}(x) = \arg\min_u\left( f(u) + \frac{1}{2 \alpha}\|u-x\|^2_2 \right) = \arg\min_u\left(|u| + \frac{1}{2 \alpha} (u-x)^2\right)$$

Найдём субдифференциал функции $g_x(u) = |u| + \frac{1}{2 \alpha} (u-x)^2$.

\begin{align}
\partial g_x(u) =
\begin{cases}
1 + \frac{1}{\alpha}(u-x)  & u > 0 \\
-1 + \frac{1}{\alpha}(u-x) & u < 0 \\
[-1;1] + \frac{1}{\alpha}(u-x) & u=0
\end{cases}
\end{align}

Решим уравнение $\partial g_x(u) = 0$

1. $$ 1 + \frac{1}{\alpha}(u-x) = 0,\ u >0$$

$$u = x - \alpha$$

Решение есть при $ x > \alpha$.

2. $$ -1 + \frac{1}{\alpha}(u-x) = 0,\ u <0$$

$$u = x + \alpha$$

Решение есть при $ x < -\alpha$.

3. $$k + \frac{1}{\alpha}(0-x) = 0,\ k \in [-1,1]$$

$$k = \frac{x}{\alpha}$$

Решение есть при $-\alpha \leq x \leq \alpha$.

Функция $g_x(u)$ выпукла, поэтому решение уравнения $\partial g_x(u) = 0$ будет минимумом функции.

В итоге получаем

\begin{align}
prox_{\alpha f}(x) =
\begin{cases}
x - \alpha & x > \alpha \\
0 &- \alpha \leq x \leq \alpha\\
x + \alpha & x < -\alpha
\end{cases}
\end{align}

### Пункт 2

Вычислим проксимацию в точке $x = x^*$.

$$prox_{\alpha f}(x^*) = \arg\min_u\left( f(u) + \frac{1}{2 \alpha}\|u-x^*\|^2_2 \right)$$

$$\forall u\ \ g(u) = f(u) + \frac{1}{2 \alpha}\|u-x^*\|^2_2 \geq  f(x^*) + \frac{1}{2 \alpha}\|x^*-x^*\|^2_2 = f(x^*) = g(x^*)$$

А значит, минимум функции $g(u) = f(u) + \frac{1}{2 \alpha}\|u-x^*\|^2_2$ достигается в точке $u = x^*$. Тогда 

$$prox_{\alpha f}(x^*) = \arg\min_u g(u) = x^*$$

In [6]:
import numpy as np

n = 5

np.random.seed(42)

A = np.random.rand(n, n)
A = A.dot(A.T)
b = np.random.randn(n)

#A = np.mat(A)

def descent(x0, eps, max_iter, alpha):
    x = x0
    for iter in range(max_iter):
        grad = A * x - b
        norm = np.linalg.norm(grad)
        #print(np.linalg.norm(grad))
        x = x - alpha * grad
        if norm < eps:
            break
    return (x, iter + 1, norm)

def prox(x0, eps, max_iter, alpha):
    x = x0
    for iter in range(max_iter):
        grad = A.dot(x) - b
        norm = np.linalg.norm(grad)
        #print(np.linalg.norm(grad))
        x = x - (np.linalg.inv(A + 1 / alpha * np.eye(n))) * grad
        if norm < eps:
            break
    return (x, iter + 1, norm)

alpha = 0.5
print(A)
print(A + 1 / alpha * np.eye(n))
print(A + 1 / alpha * np.eye(n))
print((A + 1 / alpha * np.eye(n)).dot( np.linalg.inv(A + 1 / alpha * np.eye(n))))

[[1.96268692 1.21801794 1.69464656 1.04608305 0.86611142]
 [1.21801794 1.64067514 1.03697439 0.96667309 0.89975298]
 [1.69464656 1.03697439 1.71225781 0.88036402 0.55180267]
 [1.04608305 0.96667309 0.88036402 0.67296078 0.59903033]
 [0.86611142 0.89975298 0.55180267 0.59903033 0.82139183]]
[[3.96268692 1.21801794 1.69464656 1.04608305 0.86611142]
 [1.21801794 3.64067514 1.03697439 0.96667309 0.89975298]
 [1.69464656 1.03697439 3.71225781 0.88036402 0.55180267]
 [1.04608305 0.96667309 0.88036402 2.67296078 0.59903033]
 [0.86611142 0.89975298 0.55180267 0.59903033 2.82139183]]
[[3.96268692 1.21801794 1.69464656 1.04608305 0.86611142]
 [1.21801794 3.64067514 1.03697439 0.96667309 0.89975298]
 [1.69464656 1.03697439 3.71225781 0.88036402 0.55180267]
 [1.04608305 0.96667309 0.88036402 2.67296078 0.59903033]
 [0.86611142 0.89975298 0.55180267 0.59903033 2.82139183]]
[[ 1.00000000e+00  9.29327623e-19  7.87642115e-18 -5.47642981e-17
   5.32045316e-17]
 [-7.91976538e-17  1.00000000e+00  5.66933

In [12]:
print("Градиентный спуск")
for h in [10,   1, 0.5, 0.1, 0.01,  1e-3, 1e-4]: 
    x, iter, norm = descent(np.ones(n), 1e-7, 10000, h)
    print(iter, norm, h)
print()
print("А теперь проксимальный метод")
for h in [10, 1, 0.1, 0.01, 1e-3, 1e-4]: 
    x, iter, norm = prox(np.ones(n), 1e-7, 10000, h)
    print(iter, norm, h)

Градиентный спуск
10000 nan 10
450 9.964584657407018e-08 1
54 7.622718046032597e-08 0.5
298 9.812141185007224e-08 0.1
3045 9.958565870499373e-08 0.01


<ipython-input-6-e664ade936a8>:19: RuntimeWarning: overflow encountered in multiply
  x = x - alpha * grad
<ipython-input-6-e664ade936a8>:19: RuntimeWarning: invalid value encountered in subtract
  x = x - alpha * grad


10000 0.008353269242428452 0.001
10000 2.0607735839467356 0.0001

А теперь проксимальный метод


<ipython-input-6-e664ade936a8>:30: RuntimeWarning: overflow encountered in multiply
  x = x - (np.linalg.inv(A + 1 / alpha * np.eye(n))) * grad
<ipython-input-6-e664ade936a8>:30: RuntimeWarning: overflow encountered in subtract
  x = x - (np.linalg.inv(A + 1 / alpha * np.eye(n))) * grad


10000 nan 10
10000 nan 1
10000 1.8708922815312562e+65 0.1


<ipython-input-6-e664ade936a8>:30: RuntimeWarning: invalid value encountered in subtract
  x = x - (np.linalg.inv(A + 1 / alpha * np.eye(n))) * grad


10000 44.07241872851285 0.01
10000 3.396917062785032e+20 0.05
10000 6.632885443037115 0.001
10000 11.566546543086112 0.0001


In [25]:
print(x, iter)

[[ -3.97250289  -1.18351654   0.53117777 ...  -1.95332019  65.02635074
   19.25804156]
 [-47.34012896  -1.76801963   1.23687454 ...  -0.93090509   1.86330554
    2.66424251]
 [ -2.31742736 -13.37279023   2.40563017 ...  -3.86952334   2.65361747
   24.34492443]
 ...
 [ -1.90572477  -5.23330766   0.54331972 ...  -1.29407324   3.98546024
    2.23332612]
 [ -1.8956478   -5.62567957   2.97165923 ...  -1.22845284   1.98925059
   49.95143211]
 [-64.37986445  -3.0165273    2.61323607 ...  -0.88213534   4.15839744
    9.56882066]] 999


Получилось, что градиентный спуск сходится быстрее проксимального, да ещё и начинает расходиться при бОльших $h$. Видимо, проксимальный метод криво реализован...